### ISSUE TITLE
Migrate to CE3

### ISSUE THREAD

**Issue by catostrophe** [janstenpickle/trace4cats#299]
This issue is to track dependencies and blockers.

CE3 tracking issue: typelevel/cats-effect#1330

PR with CE3 changes: #374

Dependencies affected by CE3 migration:

- [x] cats-effect - released [v3.1.0](https://github.com/typelevel/cats-effect/releases/tag/v3.1.0) - ok 🟢
- [x] fs2 - released [v3.0.2](https://github.com/typelevel/fs2/releases/tag/v3.0.2) - ok 🟢
- [x] log4cats - released [v2.1.0](https://github.com/typelevel/log4cats/releases/tag/v2.1.0) - ok 🟢
- [x] natchez - released [v0.1.2](https://github.com/tpolecat/natchez/releases/tag/v0.1.2) - ok 🟢 
- [x] decline - released [v2.0.0](https://repo1.maven.org/maven2/com/monovore/decline-effect_2.13/2.0.0/) - ok 🟢 
- [x] zio-interop-cats - released [v3.0.2.0](https://github.com/zio/interop-cats/releases/tag/v3.0.2.0) - ok 🟢 
- [x] sttp-client3 - released [v3.3.2](https://github.com/softwaremill/sttp/releases/tag/v3.3.2) - ok 🟢 
- [x] fs2-kafka - candidate [v2.0.0](https://github.com/fd4s/fs2-kafka/releases/tag/v2.0.0) - ok 🟢 
- [x] redis4cats - candidate [v1.0.0-RC3](https://github.com/profunktor/redis4cats/releases/tag/v1.0.0-RC3) - pending 🟡 
- [x] http4s - milestone [v1.0.0-M21](https://github.com/http4s/http4s/releases/tag/v1.0.0-M21) - pending 🟡 
- [x] http4s-jdk-http-client - milestone [v0.5.0-M4](https://github.com/http4s/http4s-jdk-http-client/releases/tag/v0.5.0-M4) - pending 🟡 
- [ ] tapir-http4s-server - WIP softwaremill/tapir#1154 - blocker 🔴

**Comment by catostrophe** [comment]
Dependencies affected by CE3:

- [x] fs2-kafka - released [v3.0.0-M2](https://github.com/fd4s/fs2-kafka/releases/tag/v3.0.0-M2)
- [ ] http4s - WIP [Project Cats Effect 3](https://github.com/http4s/http4s/projects/4)
- [x] log4cats - released [v2.0.0-RC1](https://github.com/typelevel/log4cats/releases/tag/v2.0.0-RC1)
- [ ] redis4cats - WIP profunktor/redis4cats#474
- [ ] decline - not started bkirwi/decline#254
- [ ] natchez - WIP tpolecat/natchez#282
- [ ] zio-cats-interop - WIP zio/interop-cats#263
- [ ] tapir-http4s-server - not started softwaremill/tapir#1050
- [ ] sttp-client - unknown
- [ ] sttp-client3 - WIP softwaremill/sttp#738

**Comment by catostrophe** [comment]
@kubukoz could you please add this issue to the tracking list in CE3?

**Comment by kubukoz** [comment]
Yeah, I'll add it later tonight :)

**Comment by kubukoz** [comment]
Also, small correction: decline is up to date with RC2: https://github.com/bkirwi/decline/pull/206

**Comment by ashwinbhaskar** [comment]
@catostrophe `natzches` already has a [milestone release](https://github.com/tpolecat/natchez/tree/v0.1.0-M4) with cats effect 3. I am closing the PR - https://github.com/tpolecat/natchez/pull/282

**Comment by ashwinbhaskar** [comment]
Should we also mention doobie here? There is a PR for it https://github.com/tpolecat/doobie/pull/1280

**Comment by catostrophe** [comment]
`redis4cats`, `decline` will have their CE3-compatible release candidates in a few days
`zio-cats-interop` and `sttp-client3` are under work and I hope we'll see their release candidates soon
 `tapir` hasn't started the migration but we use http4s integration only in tests.

**Comment by kubukoz** [comment]
Updates!

redis4cats, decline, ZIO have released

sttp has an RC (3.3.0-RC4)

tapir has a PR: https://github.com/softwaremill/tapir/pull/1154
